/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdvisorRouteImport } from './routes/advisor'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as MarketRouteImport } from './routes/market'
import { Route as RegionsRouteImport } from './routes/regions'
import { Route as UpgradesRouteImport } from './routes/upgrades'
import { Route as CombatIndexRouteImport } from './routes/combat/index'
import { Route as CombatGearRouteImport } from './routes/combat/gear'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdvisorRoute = AdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const RegionsRoute = RegionsRouteImport.update({
  id: '/regions',
  path: '/regions',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradesRoute = UpgradesRouteImport.update({
  id: '/upgrades',
  path: '/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const CombatIndexRoute = CombatIndexRouteImport.update({
  id: '/combat/',
  path: '/combat/',
  getParentRoute: () => rootRouteImport,
} as any)
const CombatGearRoute = CombatGearRouteImport.update({
  id: '/combat/gear',
  path: '/combat/gear',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/builder': typeof BuilderRoute
  '/companies': typeof CompaniesRoute
  '/market': typeof MarketRoute
  '/regions': typeof RegionsRoute
  '/upgrades': typeof UpgradesRoute
  '/combat/gear': typeof CombatGearRoute
  '/combat/': typeof CombatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/builder': typeof BuilderRoute
  '/companies': typeof CompaniesRoute
  '/market': typeof MarketRoute
  '/regions': typeof RegionsRoute
  '/upgrades': typeof UpgradesRoute
  '/combat/gear': typeof CombatGearRoute
  '/combat': typeof CombatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/advisor': typeof AdvisorRoute
  '/builder': typeof BuilderRoute
  '/companies': typeof CompaniesRoute
  '/market': typeof MarketRoute
  '/regions': typeof RegionsRoute
  '/upgrades': typeof UpgradesRoute
  '/combat/gear': typeof CombatGearRoute
  '/combat/': typeof CombatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advisor'
    | '/builder'
    | '/companies'
    | '/market'
    | '/regions'
    | '/upgrades'
    | '/combat/gear'
    | '/combat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advisor'
    | '/builder'
    | '/companies'
    | '/market'
    | '/regions'
    | '/upgrades'
    | '/combat/gear'
    | '/combat'
  id:
    | '__root__'
    | '/'
    | '/advisor'
    | '/builder'
    | '/companies'
    | '/market'
    | '/regions'
    | '/upgrades'
    | '/combat/gear'
    | '/combat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdvisorRoute: typeof AdvisorRoute
  BuilderRoute: typeof BuilderRoute
  CompaniesRoute: typeof CompaniesRoute
  MarketRoute: typeof MarketRoute
  RegionsRoute: typeof RegionsRoute
  UpgradesRoute: typeof UpgradesRoute
  CombatGearRoute: typeof CombatGearRoute
  CombatIndexRoute: typeof CombatIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/advisor': {
      id: '/advisor'
      path: '/advisor'
      fullPath: '/advisor'
      preLoaderRoute: typeof AdvisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regions': {
      id: '/regions'
      path: '/regions'
      fullPath: '/regions'
      preLoaderRoute: typeof RegionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrades': {
      id: '/upgrades'
      path: '/upgrades'
      fullPath: '/upgrades'
      preLoaderRoute: typeof UpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combat/': {
      id: '/combat/'
      path: '/combat'
      fullPath: '/combat/'
      preLoaderRoute: typeof CombatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/combat/gear': {
      id: '/combat/gear'
      path: '/combat/gear'
      fullPath: '/combat/gear'
      preLoaderRoute: typeof CombatGearRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdvisorRoute: AdvisorRoute,
  BuilderRoute: BuilderRoute,
  CompaniesRoute: CompaniesRoute,
  MarketRoute: MarketRoute,
  RegionsRoute: RegionsRoute,
  UpgradesRoute: UpgradesRoute,
  CombatGearRoute: CombatGearRoute,
  CombatIndexRoute: CombatIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
